#SPDX-License-Identifier: MIT-0
# tasks file for roles/create_network
---
- name: Create Docker network
  docker_network:
    name: app-network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
