---
- name: Launch database container
  docker_container:
    name: my-database
    image: paulmahaut/tp-database
    networks:
      - name: app-network
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - db-data:/var/lib/postgresql/data
    restart_policy: unless-stopped
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3